apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ywpb3tqew-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ywpb3tqew-nodejs 
  name: ywpb3tqew-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ywpb3tqew-nodejs 
